name: Check compilation

on:
  push:
    branches:
      - '*'
  pull_request:
    branches:
      - main

jobs:
  lint-and-build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: ['14.x', '16.x', '18.x', '20.x']

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup Node.js ${{matrix.node-version}}
        uses: actions/setup-node@v2
        with:
          node-version: ${{matrix.node-version}}

      - name: NPM Install
        run: npm install

      - name: NPM Lint
        run: npm run lint

      - name: Build
        run: npm run build
        continue-on-error: true

      - name: Check Lint
        run: |
          if [ ${{ success() }} != 'true' ]; then
            echo "La compilation a échoué."
            exit 1
          fi
